### ISSUE TITLE
SteamIDs have parsed emotes.

### ISSUE THREAD

**Issue by NanoAi** [CaveeJohnson/gmod-xp-chat#5]
I've noticed that emotes get parsed even when you don't want them to.
For example STEAM_0:1:12345678 would be turned into STEAM_0<se=1>12345678
![hl2_2017-04-15_20-57-38](https://cloud.githubusercontent.com/assets/3096584/25067858/38333a40-221e-11e7-9d10-b2d2df3caaf8.png)

PS. The only good custom chat box I could find even if it's "buggy as hell".

**Comment by CaveeJohnson** [comment]
Should have been fixed in
https://github.com/CaveeJohnson/gmod-xp-chat/commit/16239040170e76dfea0d98795209458b30f63909#diff-fd165ce83edd8c3415c16f259f112823R181
Are you certain you are using the latest version?

**Comment by NanoAi** [comment]
Hmm turns out I had it installed from a forked repo, and posted the issue here in my haste. https://github.com/PAC3-Server/gmod-xp-chat
